package com.aditya.paymentgateway

class ShopDummy {
    companion object{
        var modelShops:MutableList<ModelShop> = mutableListOf();

        fun setDataDummyALl(){
            modelShops.add(ModelShop("Sepatu Adidas",499000,"Adidas AG is a multinational corporation, founded and headquartered in Herzogenaurach, Germany, that designs and manufactures shoes, clothing and accessories. It is the largest sportswear manufacturer in Europe, and the second largest in the world, after Nike.","https://cf.shopee.co.id/file/a782a5b475f99b995245eb4b1a6a11f4"))
            modelShops.add(ModelShop("Sepatu Nike",500000,"Nike mungkin dapat dibilang salah satu merk sepatu terbaik. Sepatu Nike Air Rift sudah diproduksi Nike sejak tahun 1996 terinspirasi dari gaya para pelari jarak jauh di Kenya. Namun, karena jenisnya yang mirip dengan sepatu para ninja, akhirnya publik kerap menyebutnya Nike Ninja. Sepatu lari yang lentur, rendah dan terbuka ini cocok banget untuk dipadu dengan celana panjang yang digulung di atas tumit.","https://c.static-nike.com/a/images/t_PDP_1280_v1/f_auto/skwgyqrbfzhu6uyeh0gg/air-max-270-shoe-8HhX8Z.jpg"))
            modelShops.add(ModelShop("Sepatu Puma",360000,"Merk sepatu pria Suede Classic All Black adalah salah satu warna paling favorit dari deretan pilihan warna lainnya. Sneaker klasik pertama yang terbuat dari suede ini memiliki ciri khas aksen garis panjang yang melengkung di bagian samping tumit. Harganya cukup murah berkisar Rp900 ribuan.","https://s3.bukalapak.com/uploads/content_attachment/3193fed450e8d7620d7825c5/w-744/40536262_331628577606017_1738612442968646667_n.jpg"))
            modelShops.add(ModelShop("Sepatu New Balance",350000,"Merk sepatu sneakers satu ini didesain khusus oleh New Balance bukan untuk berolahraga, melainkan untuk hang out. Walaupun terkesan minimalis, desainnya sangat futuristik. Dengan bodi yang meruncing dan sol yang tebal, NB 247 asik untuk dipakai jalan-jalan. Gaya mankle kamu akan terlihat lebih keren dan sporty sekaligus. NB 247 tersedia dalam beberapa pilihan warna, seperti hitam, biru muda, hingga cokelat. NB 247 berkisar Rp800 ribuan.","https://s0.bukalapak.com/uploads/content_attachment/5358b1b910e8d762938223c5/w-744/4_Sepatu_Lifestyle_Dari_New_Balance_Ini_Cocok_Banget_Untuk_Gaya_Mankle_-_foto_New_Balance.jpg"))
            modelShops.add(ModelShop("Sepatu Vans",2000,"Sejarah sepatu Vans Checkerboard Slip-On dimulai pada 1977. Saat itu, Steve Van Doren, anaknya Paul Van Doren si pendiri Vans, melihat para skateboarder suka mewarnai bagian sol sepatunya dengan pola hitam-putih. Ia lalu punya ide untuk membuat motif tersebut juga, tetapi bukan di sol melainkan di bagian kanvasnya.","https://s1.bukalapak.com/uploads/content_attachment/be055d0810e8d7627e9223c5/w-744/direct_uploads_2F5378_2FEUY3LPlZLFToFJwD7AhhjQ_2FVans_Authentic_Black.jpg"))
            modelShops.add(ModelShop("Sepatu Converse",2000,"Converse adalah salah satu merk sepatu terkenal. Converse Chuck Taylor All-Stars adalah sepatu sejuta umat. Modelnya yang sederhana terbukti disukai banyak orang, bahkan tidak dari cuma kalangan sneakerhead. Namun kalau kamu bosan dengan Converse Chuck Taylor All-Stars yang terlalu sederhana, silakan coba Converse Jack Purcell.","https://s1.bukalapak.com/uploads/content_attachment/6e48dcde30e8d7627c7825c5/w-744/Airwalk-One-Charcoal-_-Grey-Skate-Shoes-_292793-front-US.jpg"))
            modelShops.add(ModelShop("Sepatu Reebok",2000,"Untuk kamu yang suka full black sneakers, harus tahu kalau Reebok punya koleksi dengan warna full hitam yang sama. Untuk dipakai jalan sehari-hari, Reebok Classic tak ada tandingannya karena tingkat kenyamanannya patut diacungi jempol. Untuk warna, merk sepatu sneakers Reebok Classic hitam ini cocok untuk dipakai ke sekolah, atau dipakai hang out sekalipun.","https://s4.bukalapak.com/uploads/content_attachment/45db9dab10e8d762289223c5/w-744/reebok_classic_black-504nps.jpg"))
            modelShops.add(ModelShop("Sepatu Piero",2000,"Satu lagi merk sepatu Indonesia yang punya berderet sneakers kece. Dari sekian banyak sepatu rilisan Piero, seri Jogger bisa dibilang menjadi yang paling menarik minat para kawula muda. Desainnya berkelas banget! Tidak kalah dengan kembarannya Newbalance 574 yang memang terkesan kembar identik.","https://s4.bukalapak.com/uploads/content_attachment/4c3dec0810e8d762746223c5/w-744/Piero_Jogger_-_Piero_Indonesi_.jpg"))
            modelShops.add(ModelShop("Sepatu League",2000,"Ada yang belum tahu kalau merk sepatu sneakers League itu adalah buatan Indonesia? Kabar baiknya lagi, desain dan kualitasnya tidak kalah dengan sneakers yang biasa terpampang di toko-toko sepatu Eropa. Salah satu varian yang keren dari League adalah League Sanchez La M. Sneakers yang sekilas mirip Reebok Classics.","https://s0.bukalapak.com/uploads/content_attachment/0cb35caa10e8d762a56223c5/w-744/League_Sanchez_-_Grandstore_bukalapak.png"))
            modelShops.add(ModelShop("Sepatu Superaga",2000,"Brand Superga tentu bukan nama asing buat kamu yang hobi mengoleksi sneakers. Merk sepatu ini terkenal dengan desainnya yang klasik dan penggunaan bahan-bahan berkualitas tinggi. Superga punya beragam jenis sneakers, termasuk edisi slip on.","https://s3.bukalapak.com/uploads/content_attachment/868ef49a10e8d762ff6223c5/w-744/SEPATU_SLIP_ON_CASUAL_SUPERGA_COTU_BLACK_ORIGINAL.jpg"))
        }

    }
}